// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omnugaurleaclnjpmzws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tbnVnYXVybGVhY2xuanBtendzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzU2NDUsImV4cCI6MjA3MTQ1MTY0NX0.S0pH-BsfJ03Jz2zvD2-L_O1ZhvFq_XR9GczomNxnWMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});